config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/OphidiaBigData/PyOphidia:
      branch: master
      repo: https://github.com/OphidiaBigData/PyOphidia
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/OphidiaBigData/PyOphidia git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-gold-havanese.sh
        container: qc.acc_chummy-brass-vulture
  QC.Doc:
    repos:
      github.com/OphidiaBigData/PyOphidia find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-sangria-tuatara.sh
        container: qc.doc_squirrely-periwinkle-duck
      github.com/OphidiaBigData/PyOphidia git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-dandelion-havanese.sh
        container: qc.doc_lousy-plum-burmese
      github.com/OphidiaBigData/PyOphidia markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-turquoise-guppy.sh
        container: qc.doc_muzzy-platinum-seal
      github.com/OphidiaBigData/PyOphidia restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-cornflower-kangaroo.sh
        container: qc.doc_geeky-magenta-tzu
  QC.Lic:
    repos:
      github.com/OphidiaBigData/PyOphidia licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-aquamarine-robin.sh
        container: qc.lic_trippy-cream-emu
  QC.Sec:
    repos:
      github.com/OphidiaBigData/PyOphidia bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-olivine-turkey.sh
        container: qc.sec_muggy-coral-grouse
  QC.Sty:
    repos:
      github.com/OphidiaBigData/PyOphidia flake8:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-smalt-cassowary.sh
        container: qc.sty_shabby-ochre-chimpanzee
  QC.Uni:
    repos:
      github.com/OphidiaBigData/PyOphidia pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-brown-mastiff.sh
        container: qc.uni_chummy-cinnabar-fousek
  QC.Ver:
    repos:
      github.com/OphidiaBigData/PyOphidia get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-taupe-lizard.sh
        container: qc.ver_squirrely-black-markhor
timeout: 5400
