config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/OphidiaBigData/PyOphidia:
      branch: master
      repo: https://github.com/OphidiaBigData/PyOphidia
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/OphidiaBigData/PyOphidia git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-cream-squirrel.sh
        container: qc.acc_scummy-buff-fox
  QC.Doc:
    repos:
      github.com/OphidiaBigData/PyOphidia find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-malachite-squirrel.sh
        container: qc.doc_cloudy-crimson-ant
      github.com/OphidiaBigData/PyOphidia git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-cream-frigatebird.sh
        container: qc.doc_cranky-mustard-angelfish
      github.com/OphidiaBigData/PyOphidia markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-magenta-vole.sh
        container: qc.doc_foggy-coral-rottweiler
      github.com/OphidiaBigData/PyOphidia restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-persimmon-eagle.sh
        container: qc.doc_pretty-dandelion-rottweiler
  QC.Lic:
    repos:
      github.com/OphidiaBigData/PyOphidia licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-cyan-neanderthal.sh
        container: qc.lic_cranky-magnolia-chow
  QC.Sec:
    repos:
      github.com/OphidiaBigData/PyOphidia bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ready-viridian-discus.sh
        container: qc.sec_sleepy-thistle-booby
  QC.Sty:
    repos:
      github.com/OphidiaBigData/PyOphidia flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-orange-gar.sh
        container: qc.sty_sickly-firebrick-mammoth
  QC.Uni:
    repos:
      github.com/OphidiaBigData/PyOphidia pytest:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-razzmatazz-bee.sh
        container: qc.uni_lousy-wisteria-newt
  QC.Ver:
    repos:
      github.com/OphidiaBigData/PyOphidia get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-lilac-barracuda.sh
        container: qc.ver_grumpy-ruby-seal
timeout: 5400
