config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/OphidiaBigData/PyOphidia:
      branch: master
      repo: https://github.com/OphidiaBigData/PyOphidia
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/OphidiaBigData/PyOphidia git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-carmine-walrus.sh
        container: qc.acc_homey-ruby-hare
  QC.Doc:
    repos:
      github.com/OphidiaBigData/PyOphidia find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-purple-chipmunk.sh
        container: qc.doc_tacky-olivine-frog
      github.com/OphidiaBigData/PyOphidia git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-malachite-panda.sh
        container: qc.doc_jumpy-azure-hedgehog
  QC.Lic:
    repos:
      github.com/OphidiaBigData/PyOphidia licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-cyan-hyena.sh
        container: qc.lic_homely-grey-tang
  QC.Ver:
    repos:
      github.com/OphidiaBigData/PyOphidia get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-cardinal-chihuahua.sh
        container: qc.ver_scaly-alizarin-pig
timeout: 5400
